apiVersion: v1 # Versi API Kubernetes dan jenis objek yang akan digunakan (Secret)
kind: Secret # Jenis objek Kubernetes yang akan dibuat (Secret)

metadata:
  name: mongo-secret # Nama Secret yang akan dibuat

type: Opaque # Tipe Secret, dalam hal ini, "Opaque" yang berarti tipe Secret umum yang dapat menyimpan data apa pun

data:
  MONGO_ROOT_USERNAME: YWRtaW4= # Data rahasia (username) yang akan disimpan dalam Secret, hasil dari encoding base64 dari "admin"
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # Data rahasia (password) yang akan disimpan dalam Secret, hasil dari encoding base64 dari "supersecretpassword"
