apiVersion: v1 # Versi API Kubernetes dan jenis objek yang akan digunakan (Service)
kind: Service # Jenis objek Kubernetes yang akan dibuat (Service)

metadata:
  name: mongo-service # Nama Service yang akan dibuat

spec:
  selector:
    app: mongodb # Selector untuk memilih pod-pod yang ingin di-associate dengan Service

  ports:
    - protocol: TCP # Protocol yang digunakan (TCP)
      port: 27017 # Port yang akan di-expose di dalam Service
      targetPort: 27017 # Port yang diarahkan ke pod-pod yang sesuai dengan selector
